name: art
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  get_it: ^7.2.0
  go_router: ^5.2.4
  google_fonts: ^5.1.0
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


  assets:
    - assets/images/
  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf